FROM openjdk:8-jdk-alpine

LABEL maintainer="berserkV"

VOLUME /tmp

EXPOSE 8081

RUN mkdir -p /app/

RUN mkdir -p /app/logs/

ADD target/animeRESTConsume-0.0.1-SNAPSHOT.jar /app/animeRestConsume.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container", "-jar", "/app/animeRestConsume.jar"]