spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/anime
    username: diego
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true 
    