server:
  port: 8081
  #port: 8080
spring:
  profiles:
    active:
    - local

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: diego
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/anime
    username: diego
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    #show-sql: true